import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/shared/Header";

import "@/styles/globals.css";
import Provider from "./provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ticket Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased max-w-desktop mx-auto px-4 sm:px-0`}
      >
        <Header />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
